name: AFKPlus
version: ${project.version}
main: net.lapismc.afkplus.AFKPlus
api-version: 1.16
softdepend: [ PlaceholderAPI ]
authors: [Dart2112, Azurin]
description: "SafeAFK: to prevent accidental deaths when you're not looking at your screen"
